name: Florian Krüger
description: Software Developer & Enthusiast
meta_description: "Blogging about tech, mostly iOS & OS X"

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://xcuze.me'
google_analytics: 'UA-59881462-1'

# Details for the RSS feed generator
url:            'www.xcuze.me'
author:         'Florian Krüger'
